### PR TITLE
Add drawable-interline-spacing

### PR DESCRIPTION
**Pull request by hannanilsson**
Hi again! August came early this year 😅 

We wanted to add the possibility to use interline-spacing, however, negative values does not seem to work. We are unable to understand why. Could you maybe have a look? Thank you!

### CODE REVIEW

**Comment by dlemstra** [comment]
Thanks for coming back so quickly to help me with this project. Would you be willing to change this PR and remove the negative value unit test? I can then merge this and investigate why the negative value is not working. It seems to be working on the command line so it should work in wasm.

**Comment by hannanilsson** [comment]
Absolutely, I have removed it now! We just wanted to add it initially to demonstrate the issue. It sounds promising that it should work with negative values, hope your investigation can find why it doesn't! 😄

**Comment by dlemstra** [comment]
Thanks for adding the test for a negative value earlier. I have found what was causing it not to work and fixed the issue in ImageMagick. This will be fixed when I upgrade Magick.Native later this week. And then I will also add a unit test for a negative value.

**Comment by hannanilsson** [comment]
Glad to hear that! Thank you for your work! ⭐️

**Pull request merged**
