### PR TITLE
Tighten code quality control

### PR DESCRIPTION
**Pull request by Peeterush**
I propose a considerably stronger ESLint ruleset to enforce best practices and a consistent code style, while requiring less effort of the programmer (ESLint's `--fix` can automatically correct many styling issues).

The configuration is build on the extremely popular [Airbnb config](https://github.com/airbnb/javascript), which has been tailored to fit the style of the existing code base.

### CODE REVIEW

**Review by dlemstra — CHANGES_REQUESTED** [review]
Not a fan of these big pull requests that change a lot of things at once. 

I would rather see a pull request for each rule you think that should be applied. I can then decide if I want to apply this rule or not.

**Comment by Peeterush** [comment]
Since the configuration is based on an external ruleset, it would be near impossible to make PRs on a per-rule basis for any rule that is not already in its own commit right now. So I propose that I give a summary for each rule and what was changed, then you can tell me if any of the rules don't sit well with you without having to dig through the diff, and I can make changes accordingly. However we go about this, any rule that has a lot of violations (e.g. `linebreak-style`) is going to have a big commit associated with it regardless.

Most rules just enforce a preexisting convention of this project. The motivation for many rules is also well explained in the [Airbnb styleguide](https://github.com/airbnb/javascript) if you want more info. It is possible that I missed some rules for best practices or styling because I did not reconfigure them and the code base already respects them, so I did not notice them.
This is the summary of the current commits, and all the rules they enforce:
<details>
<summary>View commit summary</summary>

1. Configures ESLint, but doesn't modify any of the code. `.editorconfig` was also modified to enforce LF through the editor too.
2. Automatic fixes from `eslint --fix .` only, no manual work. If you go through the diff, note that some of the changes made in this commit are corrected in commit 22. The following rules have been auto-fixed:
   - `comma-dangle`: Trailing commas simplify modifying items in objects and arrays, since only the lines modified lines are  touched. It also improves git diff clarity in such cases.
   - `order`: alphabetically sorts imports based on module name/path. This is actually the only rule that deviates from the current convention: imports are currently alphabetically sorted based on imported variable names. This new way is more diff friendly, as an import will not change position if a new member is added to the front of that import.
   - `semi`: enforces use of semicolons. JS ASI does not always work as expected, so explicitly places them where they need to be.
   - `nonblock-statement-body-position`: forces nonblock statements to sit on the same line as the `if`/`for`/whatever they belong to. This makes it clearer that only one statement belongs to the condition. AFAIK, this is the style everything JS/TS uses.
   - `indent`, `space-before-function-paren`, `comma-spacing`, `no-trailing-spaces`, `brace-style`, `padded-blocks`: consistency rules for spaces, new lines and indentation.
   - `linebreak-style`: enforces use of LF over CRLF.
   - `quotes`: enforces use of single quotes over double quotes.
   - `header`: makes sure the copyright/license header is present in every file.
   - `lines-between-class-members`: there were a couple of classes that seemed intentionally not to do this with getters/setters. But since this rule can't be configured for only non getters/setters I think it is better to enforce it everywhere rather than not at all.
   - `prefer-destructuring`: saves you from creating temporary references and repetitive object access, and overall less code.
   - `arrow-body-style`: turns arrow functions only containing a return statement into the `() => val` format, without block. This is syntactic sugar, just like arrow functions themselves.
   - `arrow-parens`: this is changed to fit existing code to disallows parenthesis around arrow functions' parameter when there's only one, diverging from the recommended best practices (always putting them is more consistent with multiple parameters, and minimizes diff churn).
   - `prefer-arrow-callback`: this is not just for conciseness. Arrow functions run in the context of the parent `this` instead of `this` referring to the function itself.
   - `object-shorthand`: forces function definitions in objects to be shorthands instead of properties containing a function. This is shorter and more descriptive.
   - `no-undef-init`: uninitialized variables will always be `undefined` already, so there's no point assigning it manually.
   - `no-unresolved`: will complain if an import can't be found.
3. `no-explicit-any`: bans use of the `any` type. If you have a typing system, use it, no exceptions. Most of the changes are for all the tests, changing the `(global as any).native` to `global.native` (the `native` property is added to the `global` type by `custom-environment.ts`).
4. `member-ordering`: enforces a consistent order of class properties. It is configured to follow the pattern seemed to be used in most files: fields, constructor, getters/setters, methods. All categories are ordered public, private, static, and each of those is sorted alphabetically.
5. `class-methods-use-this`: makes sure that instance methods use `this`, or are static methods. My resolutions sometimes remove a function as I found easier/native ways to achieve the same without a helper function.
6. `no-shadow`: disallows variable shadowing, to avoid confusion. Mostly removes code: turns out some tests were making 'global' variables they didn't use!
7. `no-new`: makes sure classes are not instantiated for side effects. This best practice is already practiced by the current code, but a couple of tests make a 'violation' for testing purposes so this commit silences the linter there.
8. `eqeqeq`: this rule enforces strict equality checks (`===` over `==`). This commit fixes 5 violations.
9. `no-console`: `tests` and `demo` are linted too, so this commit silences a few specific violations. Why not turn it off for those directories? It is still nice to be alerted of forgotten debug statements.
10. `no-restricted-syntax`: this forbids iterators. The Airbnb style guide argues that "Dealing with pure functions that return values is easier to reason about than side effects.". There were only 3 cases of for..of/for..in loops in the code base, and 2 of those had objectively easier solutions using native array functions. The new solution of the third case is arguably also easier to read.
11. `no-restricted-globals`: disallows legacy globals. This commit corrects a single use of `isNaN()` to `Number.isNaN()`.
12. `no-throw-literal`: enforces use of an `Error` object instead of literal strings. Error objects automatically keep track of where they were built and originated. This commit fixes 1 violation.
13. `export`: the `index.ts` file accidentally exported everything from `./image-magick` twice. This rule finds these kind of issues.
14. `consistent-return`: this rule makes sure a function consistently returns something or nothing at all. There were 2 functions that in some specific cases used `return`, while they never should.
15. `naming-convention`: there was actually nothing to fix here, there's no unwelcome snake_case or whatever to be found. But the `ColorSpace` enum does deviate from the enum PascalCase convention, so this commit silences the linter there.
16. `no-unused-expressions`: this seems pretty logical, unused expressions are basically dead code. There was 1 violation, and 1 case where it is necessary for a test. This commit fixes the first and silences the second.
17. `default-case`: its better to explicitly state default behavior, otherwise maybe the developer forgot to add it. Fixes 1 violation.
18. `brace-style`: this rule is actually autofixable, but in one location this was not possible because a comment was in the way.
19. `max-classes-per-file`: best practices dictate each file only declare one class, so this commit separates `test-file` from `test-files`.
20. `sort-imports`: imports lines were already sorted, but import members were not. This commit enforces this too and auto-fixes one violation.
21. `require-await`: some functions are declared async, but never do anything async. This fixed 4 locations where this happens.
22. While fixing all non-auto-fixable issues and going over the git diffs, I manually corrected a lot of things that either were fixed to a less readable state by ESLint (for example because of missing rules like `max-len`) or that were already written poorly. This commit can maybe be broken down into smaller ones.

</details>

Let me know your thoughts!

**Comment by dlemstra** [comment]
I wonder if I could not just enable the following settings instead:

```
"plugin:@typescript-eslint/recommended",
"plugin:@typescript-eslint/recommended-requiring-type-checking",
"plugin:@typescript-eslint/strict"
``

Instead of using some company specific configuration.

**Comment by Peeterush** [comment]
I just checked your changes from the weekend and it seems you've been implementing part of my changes yourself. As I genuinely enjoy contributing here, can I ask you to include me in the process when I show you something you like?

**Comment by dlemstra** [comment]
I have made some of the changes because this PR made me wonder why I had some excludes for rules. And I fixed that. 

There are some ideas that I like in this PR:
- "plugins": ["header"]
- Some of the code style changes

And also some things that I don't like:
- I really don't want to switch to the airbnb rules. 
- end_of_line = lf
- The `.eslintrc.json` in your PR looks a bit big and I would prefer to keep it simple.
- Some of the code style changes

I would not mind a PR for the `header` plugin but a lot of the style changes I don't want. And going through them separately and addressing them will take lot of time from me. With a smaller PR it's much easier to review the changes.

**Comment by dlemstra** [comment]
I think it would be wise to close this PR and maybe start a discussion about what we should change? Your thoughts @Peeterush?

**Comment by dlemstra** [comment]
I am not sure how and if I want to move forward to it. If you want to continue with this then please start a new  discussion about this. I don't want you to waste time on something that I would not want to add to this project. Also wondering if we could resolve some of the styling with something like Prettier (https://prettier.io/)?

**Pull request closed without merging**
