### PR TITLE
Introduce a build step

### PR DESCRIPTION
**Pull request by Peeterush**
I propose to change how this package is distributed.
 - By introducing a proper build step, issues like #41 are resolved, imports can be made from a single module instead of having to import everything from its own file, and `@dlemstra/magick-native` can be kept external.
 - Changing the structure to a more standard one: es module and umd module files together with a type definition in a dist folder, linked from `package.json`. Just like `NOTICE`, `license.txt` is renamed to `LICENSE` and `readme.md` is renamed to `README.md`.

`build`, `demo` and `test` are all updated to work with the new setup. Users only need to update all of their imports to come from the main module, `@imagemagick/magick-wasm`, no more submodules.

All `tests/**/*.ts` files import components from this library from `src`, but `custom-environment.js` used to import from `lib`. So when I came across it to update it to `dist`, I figured in this case it would be more logical to update it to import from `src` as well. This means that `test` can now be ran without having to `build` first.

Since the `.d.ts` file in `dist` does not carry the exact same name as the `.js` file(s) that it defines, it is not automatically associated with them. This association is only made by the package as a whole given the `exports` and `types` fields in `package.json`. This means that the original import as done in `demo.ts` could not just be changed from `lib` to `dist`, as TS would complain about missing types. By setting the `tsconfig.json` `module` field to `Node16` (Node 12 or higher), packages can import via self reference. This means `demo.ts` now consumes the package exactly how any other project would.

I didn't quite figure out how this package was packed and published, but I've done my best to include everything from previous versions;
- `NOTICE` still gets copied over from the now external `@dlemstra/magick-native`, and is staged for `npm pack`/`npm publish` inclusion by the `files` array in `package.json`.
- Everything from the `package.json` and `README.md` that where in the `lib` folder 
- `package.json`, `LICENSE` and `README.md` are all included by npm by default.
- The es and umd modules together with a type declaration file are included by the `package.json` `files` array.
- I estimated the right configuration for `.github/workflows/main.yml`, but you'd probably need to verify this.

### CODE REVIEW

**Comment by dlemstra** [comment]
Thanks for your PR, Don't think I will be able to look at this soon because I am occupied with other things. But I do have a first questions after a quick glance. Why do I need vite to build the dist?

**Comment by Peeterush** [comment]
This package needs a build step with either ignores or polyfills for `ws`, `fs`, `child_process`, `crypto` and `path`. In #41 I addressed this for Vite, but the same problem occurs in Webpack. That is why [Armster15/imagemagick-wasm-builds](https://github.com/Armster15/imagemagick-wasm-builds) was created, which even uses both ignores and polyfills. I assume this is because it wasn't clear yet that all of them can be ignored.

But this weird setup shouldn't be necessary for every project that wants to use this package. The `tsc` 'build' step that is used currently only splits the typescript definition from the javascript, but doesn't transform or bundle any modules. This is also why `@dlemstra/magick-native` has to be copied over to `src` instead of just being imported.

Properly building using a bundler solves both issues. The resulting package can be used in any project without further configuration; just install it, import what you need and build your project without changing anything.

This build step could also be done with Webpack of course, but I chose Vite because it is generally faster and easier to configure.

**Comment by Peeterush** [comment]
I just added some more changes: the original PR's move to Vite makes the transition from Jest to Vitest very easy. This commit does exactly that. This means blazing fast testing: Jest takes 88s for the full test suite, but Vitest does it in 18s. That is 4.8x as fast!

**Comment by dlemstra** [comment]
I have checked your PR and I am wondering if we could merge this in smaller steps? So it is more clear why certain changes were done? Maybe start with using a single package.json file? Or was that change made because of something else? I also don't mind breaking this up into smaller changes myself.

**Comment by dlemstra** [comment]
Why do we need both of these files: `index.mjs` and `index.umd.js`?

**Comment by Peeterush** [comment]
> I have checked your PR and I am wondering if we could merge this in smaller steps? So it is more clear why certain changes were done? Maybe start with using a single package.json file? Or was that change made because of something else? I also don't mind breaking this up into smaller changes myself.

I don't know when I have the time yet, but I can break it into pieces!
The single `package.json` change was both because Vite automatically empties the output directory before building and because two `package.json` files is not needed for a repo containing only one project. And it was also part of the general change to a more standard package structure.

> Why do we need both of these files: `index.mjs` and `index.umd.js`?

`.mjs` is the ESM format. ESM is the default JS/TS module format going forward, also supporting stuff like tree shaking and asynchronous imports. `.umd.js` is the UMD format, which is provided as a fallback for older versions of bundlers and NodeJS that can only import CJS or AMD modules. This way of distribution can also be seen in other libraries like [Vue](https://github.com/vuejs/core/blob/main/packages/vue/package.json), [websocket](https://github.com/websockets/ws/blob/master/package.json) and [Axios](https://github.com/axios/axios/blob/v1.x/package.json).

**Comment by dlemstra** [comment]
Would you mind if I picked stuff from your pull request and make some of these changes myself?

**Comment by Peeterush** [comment]
Not knowing when I have time is about the exact day as my weekend activities are weather bound. But I'm sure I'll be able to work on this by Monday or Tuesday at the latest. If you need this sooner I guess you can pick stuff apart...

**Comment by dlemstra** [comment]
I am not in a hurry just wanted to offer some help but I will wait for you to make these changes. Take the time that you need.

**Comment by dlemstra** [comment]
Thanks for splitting the PR in separate commits.

**Pull request merged**
